# Generated by Django 4.0.3 on 2022-03-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null='false')),
                ('desc', models.TextField(max_length=1000, null='false')),
                ('priority', models.CharField(choices=[('niski', 'NISKI'), ('normalny', 'NORMALNY'), ('wysoki', 'WYSOKI')], default='niski', max_length=10, null='false')),
                ('status', models.CharField(default='Created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
