# Generated by Django 4.0.3 on 2022-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default='2022-03-28 21:54'),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(default='opis', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Niski', 'Niski'), ('Normalny', 'Normalny'), ('Wysoki', 'Wysoki')], default='Niski', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Stworzono', 'Stworzono'), ('W trakcie', 'W trakcie'), ('Częściowo rozwiązany', 'Częściowo rozwiązany'), ('Rozwiązany', 'Rozwiązany'), ('Zamknięty', 'Zamknięty')], default='Stworzono', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateField(default='2022-03-28 21:54'),
        ),
    ]
