# Generated by Django 4.0.3 on 2022-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
