# Generated by Django 4.0.3 on 2022-04-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_remove_task_picture_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='url',
        ),
    ]
