# Generated by Django 4.0.3 on 2022-04-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_rename_url_picture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='author',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='task',
        ),
        migrations.AddField(
            model_name='picture',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.comment'),
            preserve_default=False,
        ),
    ]
