# Generated by Django 4.0.3 on 2022-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
