# Generated by Django 4.0.3 on 2022-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_comment_text_alter_picture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
